### ISSUE TITLE
[Android] ARK: Ultimate Mobile Edition

### ISSUE THREAD

**Issue by CYPH3RsD0M41N** [Jetup13/Retroid-Pocket-5-Wiki#28]
Game Name|Playable|Controller Support|Fixes/Notes|
:--------|:------:|:-----------------:|:----------|
[ARK: Ultimate Mobile Edition](https://play.google.com/store/apps/details?id=com.studiowildcard.arkuse)|🟦🟪|🟧|Side-loading the game through AuroraStore will not allow you to properly purchase any DLCs or MTXs. Game is playable, otherwise.

**Comment by Jetup13** [comment]
It's already on the list but it seems to allow me to purchase DLC and Ark Pass. Now, I'm unsure if the purchase would go through since I really don't want to spend money on this game 😅

If its like most other games/apps, you must have signed into your devices Google Play account on Aurora Store so GMS is properly linked
 
![Screenshot_20241219-121928 1](https://github.com/user-attachments/assets/3ae91112-c3c0-4c15-b0b4-bca1874f90b6)

**Comment by CYPH3RsD0M41N** [comment]
Hmmm. Alright, then.
